name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Test Core
      run: |
        cd core
        npm install
        npm run test
        cd ..

    - name: Test Nbt
      run: |
        cd nbt
        npm install
        npm run test
        cd ..
